#test环境
server:
  port: 18300
  context-path: /api/systemCenter
spring:
  profiles: test2
  application:
    name: b2b-systemCenter

  datasource:
        name: sp_db
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.96.30.236:3306/sp_db?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false
        type: com.alibaba.druid.pool.DruidDataSource
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: true
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        username: sp_user
        password: 123456
        filters: log4j

  #accesstoken加密串
  accessKey: 535bb3fdd47250f2dc7f2c617a835698


  #销售经理下级代理每级能招募数量
  numberLimit: 15

#分销中心url
fxUrl: http://zjdev.fingercrm.cn
#游客虚拟分组
GNO: 15125085666499PLOE7AF014XT2YMWP4V

mq:
  appId: SP
  appSecret: 0E6A12D3A2421A876715DC66AE3F283D
  requestUrl: http://dw.test.fingercrm.cn/data-warehouse
